RAW_HOSPITALS			= 'Raw Datasets/hospitals.csv'
RAW_MEDICAL_CENTERS 	= 'Raw Datasets/medical_centers.csv'
RAW_DEMOGRAPHICS_2016 	= 'Raw Datasets/IndicadoresDistritos2016.xls'
RAW_DEMOGRAPHICS_2017 	= 'Raw Datasets/IndicadoresDistritos2017.xls'
RAW_DEMOGRAPHICS_2018 	= 'Raw Datasets/PANEL_INDICADORES_2018.xls'

SAMUR_2017				= 'Processed Datasets/Dataset_SAMUR_2017.csv'
SAMUR_2018				= 'Processed Datasets/Dataset_SAMUR_2018.csv'
SAMUR_2019				= 'Processed Datasets/Dataset_SAMUR_2019.csv'
DISTRICTS				= 'Processed Datasets/distritos_municipio_madrid.csv'
MEDICAL_CENTERS_TIMES	= 'Processed Datasets/medical_centers_times.csv'
SAMUR 					= 'Processed Datasets/Dataset_SAMUR.csv'
MEDICAL_CENTERS			= 'Processed Datasets/medical_centers.csv'
HOSPITALS 				= 'Processed Datasets/hospitals.csv'
HOSPITALS_YAML 			= 'Processed Datasets/hospitals.yaml'
DEMOGRAPHICS			= 'Processed Datasets/demographics.csv'
SAMUR_MERGED			= 'Processed Datasets/Dataset_SAMUR_{0}.csv'